<?php

namespace VehturiinikShopBundle\Repository;

use VehturiinikShopBundle\Entity\Category;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllAvailable()
    {
        return $this->createQueryBuilder('c')
            ->select('c')
            ->where('c.dateDeleted IS NULL')
            ->orderBy('c.dateAdded','DESC');
    }
}
