<?php

namespace VehturiinikShopBundle\Repository;

use Proxies\__CG__\VehturiinikShopBundle\Entity\Product;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return Product[]
     */
    public function findFirstFive()
    {
       return $this->getEntityManager()
            ->getRepository(Product::class)
            ->createQueryBuilder('p')
            ->select('p')
            ->where('p.quantity > 0')
            ->orderBy('p.dateAdded','DESC')
            ->setMaxResults(5)
            ->getQuery()
            ->getResult();
    }

}
