<?php

namespace VehturiinikShopBundle\Repository;

use VehturiinikShopBundle\Entity\Product;


/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return Product[]
     */
    public function findFirstFive()
    {
       return $this->getEntityManager()
            ->getRepository(Product::class)
            ->createQueryBuilder('p')
            ->innerJoin('p.category','c')
            ->where('p.quantity > 0')
            ->andWhere('p.dateDeleted IS NULL')
            ->andWhere('c.dateDeleted IS NULL')
            ->orderBy('p.dateAdded','DESC')
            ->setMaxResults(5)
            ->getQuery()
            ->getResult();
    }
}
