<?php

namespace VehturiinikShopBundle\Repository;

use VehturiinikShopBundle\Entity\User;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllQuery()
    {
        return $this->createQueryBuilder('u')
            ->orderBy('u.dateRegistered','DESC');
    }
}
