# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.twig_extension:
        class: VehturiinikShopBundle\Twig\AppExtension
        public: false
        tags:
            - { name: twig.extension }
    app.product_service:
            class:     VehturiinikShopBundle\Service\ProductService
            arguments: ['@doctrine.orm.entity_manager']